#!/bin/sh

SYSTEM_TYPE=$(uname -s)
SSH_REPO_URL="git@github.com:basbassbasss/Dotfiles.git"

if [ "$SYSTEM_TYPE" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

fi

# Set iTerm2 prefs folder to ~/.iterm2
if [ "$SYSTEM_TYPE" = "Darwin" ]; then

  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm prefs directory.."
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
  fi

fi

# Set yadm origin url to ssh
echo "Updating the yadm origin to ssh.."
yadm remote set-url origin "$SSH_REPO_URL"

echo "Done!"